### ISSUE TITLE
Error when running make

### ISSUE THREAD

**Issue by ChriZathens** [Motion-Project/motion#147]
Hi guys!
I am using ubuntu 12.04 and have ( a very long time ago ) installed motion 3.2.12, using apt-get
I am also running motioneye as a frontend and deviced I should upgrade my motion installation to something newer, in order to also support .mp4 files etc
So downloaded the source from github and run configure without issues.
But when I run make, I get the following:
```
> # make
Welcome to the setup procedure for Motion, the motion detection daemon! If you get
error messages during this procedure, please report them to the mailing list. The
Motion Guide contains all information you should need to get Motion up and running.

Version: 3.4.1+git
Platform: Linux (if this is incorrect, please read README.FreeBSD)

Generating dependencies, please wait...

Compiling Motion object files...
--------------------------------------------------------------------------------
gcc -g -O2 -D_REENTRANT -DMOTION_V4L2 -DTYPE_32BIT="int" -DHAVE_BSWAP   -march=native -mtune=native -Wall -DVERSION=\"3.4.1+git\" -Dsysconfdir=\"/usr/local/etc\"     -c -o motion.o motion.c
gcc -g -O2 -D_REENTRANT -DMOTION_V4L2 -DTYPE_32BIT="int" -DHAVE_BSWAP   -march=native -mtune=native -Wall -DVERSION=\"3.4.1+git\" -Dsysconfdir=\"/usr/local/etc\"     -c -o logger.o logger.c
gcc -g -O2 -D_REENTRANT -DMOTION_V4L2 -DTYPE_32BIT="int" -DHAVE_BSWAP   -march=native -mtune=native -Wall -DVERSION=\"3.4.1+git\" -Dsysconfdir=\"/usr/local/etc\"     -c -o conf.o conf.c
gcc -g -O2 -D_REENTRANT -DMOTION_V4L2 -DTYPE_32BIT="int" -DHAVE_BSWAP   -march=native -mtune=native -Wall -DVERSION=\"3.4.1+git\" -Dsysconfdir=\"/usr/local/etc\"     -c -o draw.o draw.c
gcc -g -O2 -D_REENTRANT -DMOTION_V4L2 -DTYPE_32BIT="int" -DHAVE_BSWAP   -march=native -mtune=native -Wall -DVERSION=\"3.4.1+git\" -Dsysconfdir=\"/usr/local/etc\"     -c -o jpegutils.o jpegutils.c
gcc -g -O2 -D_REENTRANT -DMOTION_V4L2 -DTYPE_32BIT="int" -DHAVE_BSWAP   -march=native -mtune=native -Wall -DVERSION=\"3.4.1+git\" -Dsysconfdir=\"/usr/local/etc\"     -c -o vloopback_motion.o vloopback_motion.c
vloopback_motion.c: In function βv4l_open_vidpipeβ:
vloopback_motion.c:48:15: warning: variable βostatusβ set but not used [-Wunused-but-set-variable]
vloopback_motion.c:44:15: warning: variable βloopβ set but not used [-Wunused-but-set-variable]
vloopback_motion.c: In function βv4l_startpipeβ:
vloopback_motion.c:185:26: error: storage size of βvid_picβ isnβt known
vloopback_motion.c:186:25: error: storage size of βvid_winβ isnβt known
vloopback_motion.c:202:20: error: βVIDIOCGPICTβ undeclared (first use in this function)
vloopback_motion.c:202:20: note: each undeclared identifier is reported only once for each function it appears in
vloopback_motion.c:209:20: error: βVIDIOCSPICTβ undeclared (first use in this function)
vloopback_motion.c:214:20: error: βVIDIOCGWINβ undeclared (first use in this function)
vloopback_motion.c:222:20: error: βVIDIOCSWINβ undeclared (first use in this function)
vloopback_motion.c:186:25: warning: unused variable βvid_winβ [-Wunused-variable]
vloopback_motion.c:185:26: warning: unused variable βvid_picβ [-Wunused-variable]
make: *** [vloopback_motion.o] Error 1
```

**Any ideas????**

**Comment by Mr-Dave** [comment]
I had thought that 12.04(precise) was past EOL but since it is not, I built deb packages for it [here](https://github.com/Motion-Project/motion/releases).  This should be a easier upgrade since you should be able to install via the gdebi tool and skip the whole building process.  If you still want to build, you may be better asking the mailing list.  I have never experienced this issue and can only guess that it is something to do whether you have only the v4l libs or the v4l2 libs installed.

**Comment by tosiara** [comment]
This has been reported many times before, but I thought it is fixed in latest motion?

http://www.lavrsen.dk/foswiki/bin/view/Motion/BugReport2012x07x20x062402
http://www.lavrsen.dk/foswiki/bin/view/Motion/BugReport2012x06x23x091749
http://www.lavrsen.dk/foswiki/bin/view/Motion/BugReport2013x02x05x024206

**Comment by tosiara** [comment]
There was a workaround for v4l/v4l2 header issue. You can try to modify `track.h`, and add there a line:
```
#include <linux/videodev2.h>
```
This previously helped me to workaround similar compile errors on an older systems

**Comment by ChriZathens** [comment]
Thanks for the help guys!
I will initially try with the deb package - Mr-Dave thanks for them
A quick question because I am not confident enough:
Before installing the deb, should I first uninstall 3.2.12 version, or it should upgrade it? (motion is installed in /usr/bin/motion currently)

**Comment by ChriZathens** [comment]
OK, I finally installed it and it indeed upgraded the existing version.
The reason I wanted to perform the upgrade is because I wanted the option to save motion videos as mp4
However in motioneye I still do not see this option....

**Comment by tosiara** [comment]
To create MP4 files you need to change your motion's config file to use `extpipe` instead of built-in ffmpeg

**Comment by ChriZathens** [comment]
The thing is that I don't use motion's conf file at all
motioneye is supposed to take care of this..
I will post a question to ccrisan and see how it goes
Thanks for all the help so far - you are great!

**Comment by ccrisan** [comment]
@ChriZathens you're right - motionEye should allow you to choose mp4/h264 as codec when using the 3.4 version. The problem is that motionEye does not (yet) recognize the 3.4 version; it previously considered everything that contained "git" to be new and to support all the new features. Now that we have a 3.4 version, I'll need to update motionEye to act accordingly.

**Comment by ChriZathens** [comment]
Oh, OK, great then..
Once again thanks to everyone!
